class MainPage:
    """Header content"""
    CURRENCY_MENU = "div.pull-left button"
    MY_ACCOUNT = "a[title='My Account']"
    WISH_LIST = "#wishlist-total"
    SHOPPING_CART = "a[title='Shopping Cart']"
    CHECKOUT = "a[title='Checkout']"

    """Main content"""
    NAV_LINKS = "ul.nav > li"
    PROMOBLOCK = "swiper-viewport"
    SEARCH_INPUT = "#search"
    SEARCH_BUTTON = "#search button"
    OPEN_CART = "#cart-total"
    DESKTOPS_MENU = "Desktops"
    LAPTOPS_MENU = "Laptops & Notebooks"
    COMPONENTS_MENU = "Components"
    TABLETS_MENU = "Tablets"
    SOFTWARE_MENU = "Software"
    PHONES_MENU = "Phones & PDAs"
    CAMERAS_MENU = "Cameras"
    MP3_PLAYERS_MENU = "MP3 Players"
    CAROUSEL_NEXT = "#carousel0 + div + div div.swiper-button-next"
    CAROUSEL_PREV = "#carousel0 + div + div div.swiper-button-next"
    SLIDE_NEXT = "#slideshow0 + div + div div.swiper-button-next"
    SLIDE_PREV = "#slideshow0 + div + div div.swiper-button-prev"
    FEATURED_PRODUCT = "div.product-layout a"
    ADD_TO_CART = "div.product-layout div.caption + div.button-group button"
    ADD_TO_WISH_LIST = "button[data-original-title='Add to Wish List']"
    COMPARE_THIS_PRODUCT = "button[data-original-title='Compare this Product']"

    """Footer content"""
    ABOUT_US = "About Us"
    DELIVERY_INFORMATION = "Delivery information"
    PRIVACY_POLICY = "Privacy Policy"
    TERMS_AND_CONDITIONS = "Terms & Conditions"
    CONTACT_US = "Contact Us"
    RETURNS = "Returns"
    SITE_MAP = "Site Map"
    BRANDS = "Brands"
    GIFT_CERTIFICATES = "Gift Certificates"
    AFFILIATE = "Affiliate"
    SPECIALS = "Specials"
    MY_ACCOUNT_FROM_FOOTER = "My account"
    OLDER_HISTORY = "Older History"
    WISH_LIST_FROM_FOOTER = "Wish List"
    NEWSLETTER = "Newsletter"
